version: "3.9"

services:
    db:
        image: mariadb
        container_name: mariadb 
        restart: on-failure
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3333:3306

    adminer:
        image: adminer
        container_name: adminer
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8080:8080

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: on-failure
        depends_on:
            - db
        ports:
            - 9090:80

    php:
        image: dekpo/custom-php8
        container_name: php
        depends_on:
            - db
        ports:
            - 1975:80
            - 443:443
        volumes:
            - ./my_mini_post:/var/www/